package repo

func (r *Repo) baseTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"errors"
	"sync"

	"gorm.io/gorm"

	"{{.GormDBVarPkg}}"

	"{{.GenQueryPkg}}"
)

var once sync.Once
var q *query.Query

func GetQuery() *query.Query {
	once.Do(func() {
		q = query.Use({{.GormDBVar}})
	})
	return q
}

func IsRealErr(err error) bool {
	return !errors.Is(err, gorm.ErrRecordNotFound) && !errors.Is(err, context.DeadlineExceeded) && !errors.Is(err, context.Canceled)
}
`
}
