package repository

func (r *Repository) baseTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"errors"
	"sync"

	"gorm.io/gorm"

	"{{.GormDBVarPkg}}"

	"{{.GenQueryPkg}}"
)

var once sync.Once
var q *query.Query

func GetQuery() *query.Query {
	once.Do(func() {
		q = query.Use({{.GormDBVar}})
	})
	return q
}

// IsRealErr 是否为非超时和查询不到的错误
func IsRealErr(err error) bool {
	return !errors.Is(err, gorm.ErrRecordNotFound) &&
		!errors.Is(err, context.DeadlineExceeded) &&
		!errors.Is(err, context.Canceled)
}
`
}

func (r *Repository) genBaseTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
{{range .Imports}}{{.}}{{end}}
)

// {{.StructName}} 仓库/Repository
type {{.StructName}} struct {
	q            *query.Query
	db           *gorm.DB
	logger       *zap.Logger
	unscoped     bool
	newTableName *string
}

// Option {{.StructName}}仓库初始化选项
type Option func(*{{.StructName}})

func WithQuery(q *query.Query) Option {
	return func({{.Abbr}} *{{.StructName}}) {
		{{.Abbr}}.q = q
	}
}

func WithLogger(logger *zap.Logger) Option {
	return func({{.Abbr}} *{{.StructName}}) {
		{{.Abbr}}.logger = logger
	}
}

func WithDB(db *gorm.DB) Option {
	return func({{.Abbr}} *{{.StructName}}) {
		{{.Abbr}}.db = db
	}
}

func WithNewTableName(newTableName string) Option {
	return func({{.Abbr}} *{{.StructName}}) {
		{{.Abbr}}.newTableName = &newTableName
	}
}

func WithUnscoped() Option {
	return func({{.Abbr}} *{{.StructName}}) {
		{{.Abbr}}.unscoped = true
	}
}

// New {{.StructName}}仓库初始化
func New(opts ...Option) *{{.StructName}} {
	{{.Abbr}} := &{{.StructName}}{
		q:      {{.RepoPkgName}}.GetQuery(),
		db:     {{.GormDBVar}},
		logger: {{.ZapVar}},
	}
	for _, opt := range opts {
		opt({{.Abbr}})
	}
	return {{.Abbr}}
}

// ConditionOption 字段条件筛选选项
type ConditionOption func(*{{.StructName}}) gen.Condition

// Condition 自定义字段条件筛选
func Condition(condition gen.Condition) ConditionOption {
	return func(*{{.StructName}}) gen.Condition {
		return condition
	}
}
{{range .Conditions}}{{.}}{{end}}
// UpdateOption 数据更新选项
type UpdateOption func(*{{.StructName}}) field.AssignExpr

// Update 自定义数据更新
func Update(update field.AssignExpr) UpdateOption {
    return func(*{{.StructName}}) field.AssignExpr {
        return update
    }
}
{{range .Updates}}{{.}}{{end}}
// OrderOption 数据排序选项
type OrderOption func(*{{.StructName}}) field.Expr

// Order 自定义数据排序
func OrderBy(order field.Expr) OrderOption {
    return func(*{{.StructName}}) field.Expr {
        return order
    }
}
{{range .Orders}}{{.}}{{end}}
// RelationOption 关联模型预加载选项
type RelationOption func(*{{.StructName}}) field.RelationField

// Relation 自定义关联模型预加载
func Relation(relation field.RelationField) RelationOption {
	return func(*{{.StructName}}) field.RelationField {
		return relation
	}
}

func RelationAll() RelationOption {
	return func(*{{.StructName}}) field.RelationField {
		return field.Associations
	}
}
`
}

func (r *Repository) genCountTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _count struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
}

// Count 获取数据总条数
func ({{.Abbr}} *{{.StructName}}) Count() *_count {
	return &_count{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (c *_count) Tx(tx *query.Query) *_count {
	c.tx = tx
	if tx != nil {
		c.qTx = nil
	}
	return c
}

// QueryTx 设置为手动事务
func (c *_count) QueryTx(tx *query.QueryTx) *_count {
	c.qTx = tx
	if tx != nil {
		c.tx = nil
	}
	return c
}

func (c *_count) Unscoped() *_count {
	c.unscoped = true
	return c
}

func (c *_count) Where(opts ...ConditionOption) *_count {
	c.conditionOpts = append(c.conditionOpts, opts...)
	return c
}

// Do 执行获取数据总条数
func (c *_count) Do(ctx context.Context) (int64, error) {
	cq := c.core.q.{{.StructName}}
	if c.tx != nil {
		cq = c.tx.{{.StructName}}
	}
	if c.qTx != nil {
		cq = c.qTx.{{.StructName}}
	}
	cr := cq.WithContext(ctx)
	if c.core.newTableName != nil && *c.core.newTableName != "" {
		cr = cq.Table(*c.core.newTableName).WithContext(ctx)
	}
	if c.unscoped {
		cr = cr.Unscoped()
	}
	if len(c.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(c.conditionOpts))
		for _, opt := range c.conditionOpts {
			conditions = append(conditions, opt(c.core))
		}
		if len(conditions) > 0 {
			cr = cr.Where(conditions...)
		}
	}
	count, err := cr.Count()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			c.core.logger.Error("【{{.StructName}}.Count】失败", zap.Error(err))
		}
		return 0, err
	}
	return count, nil
}
`
}

func (r *Repository) genCreateTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _create struct {
	core      *{{.StructName}}
	tx        *query.Query
	qTx       *query.QueryTx
	unscoped  bool
	values    []*{{.ModelName}}.{{.StructName}}
	batchSize int
}

// Create 添加数据
func ({{.Abbr}} *{{.StructName}}) Create() *_create {
	return &_create{
		core:     {{.Abbr}},
		unscoped: {{.Abbr}}.unscoped,
		values:   make([]*{{.ModelName}}.{{.StructName}}, 0),
	}
}

// Tx 设置为事务
func (c *_create) Tx(tx *query.Query) *_create {
	c.tx = tx
	if tx != nil {
		c.qTx = nil
	}
	return c
}

// QueryTx 设置为手动事务
func (c *_create) QueryTx(tx *query.QueryTx) *_create {
	c.qTx = tx
	if tx != nil {
		c.tx = nil
	}
	return c
}

func (c *_create) Unscoped() *_create {
	c.unscoped = true
	return c
}

func (c *_create) Values(values ...*{{.ModelName}}.{{.StructName}}) *_create {
	c.values = append(c.values, values...)
	return c
}

// BatchSize 当批量插入时指定创建的数量
func (c *_create) BatchSize(batchSize uint) *_create {
	c.batchSize = int(batchSize)
	return c
}

// Do 执行添加数据
func (c *_create) Do(ctx context.Context) (err error) {
	length := len(c.values)
	if length == 0 {
		return nil
	}
	cq := c.core.q.{{.StructName}}
	if c.tx != nil {
		cq = c.tx.{{.StructName}}
	}
	if c.qTx != nil {
		cq = c.qTx.{{.StructName}}
	}
	cr := cq.WithContext(ctx)
	if c.core.newTableName != nil && *c.core.newTableName != "" {
		cr = cq.Table(*c.core.newTableName).WithContext(ctx)
	}
	if c.unscoped {
		cr = cr.Unscoped()
	}
	if length > 1 && c.batchSize > 0 {
		err = cr.CreateInBatches(c.values, c.batchSize)
	} else {
		err = cr.Create(c.values...)
	}
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			c.core.logger.Error("【{{.StructName}}.Create】失败", zap.Error(err))
		}
		return err
	}
	return nil
}
`
}

func (r *Repository) genDeleteTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
    "gorm.io/gen"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _delete struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
}

// Delete 删除数据
func ({{.Abbr}} *{{.StructName}}) Delete() *_delete {
	return &_delete{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (d *_delete) Tx(tx *query.Query) *_delete {
	d.tx = tx
	if tx != nil {
		d.qTx = nil
	}
	return d
}

// QueryTx 设置为手动事务
func (d *_delete) QueryTx(tx *query.QueryTx) *_delete {
	d.qTx = tx
	if tx != nil {
		d.tx = nil
	}
	return d
}

func (d *_delete) Unscoped() *_delete {
	d.unscoped = true
	return d
}

func (d *_delete) Where(opts ...ConditionOption) *_delete {
	d.conditionOpts = append(d.conditionOpts, opts...)
	return d
}

// Do 执行删除数据
func (d *_delete) Do(ctx context.Context) (int64, error) {
	dq := d.core.q.{{.StructName}}
	if d.tx != nil {
		dq = d.tx.{{.StructName}}
	}
	if d.qTx != nil {
		dq = d.qTx.{{.StructName}}
	}
	dr := dq.WithContext(ctx)
	if d.core.newTableName != nil && *d.core.newTableName != "" {
		dr = dq.Table(*d.core.newTableName).WithContext(ctx)
	}
	if d.unscoped {
		dr = dr.Unscoped()
	}
	if len(d.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(d.conditionOpts))
		for _, opt := range d.conditionOpts {
			conditions = append(conditions, opt(d.core))
		}
		if len(conditions) > 0 {
			dr = dr.Where(conditions...)
		}
	}
	res, err := dr.Delete()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			d.core.logger.Error("【{{.StructName}}.Delete】失败", zap.Error(err))
		}
		return 0, err
	}
	return res.RowsAffected, nil
}
`
}

func (r *Repository) genFirstTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _first struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	conditionOpts []ConditionOption
}

// First 获取第一条记录（主键升序）
func ({{.Abbr}} *{{.StructName}}) First() *_first {
	return &_first{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (f *_first) Tx(tx *query.Query) *_first {
	f.tx = tx
	if tx != nil {
		f.qTx = nil
	}
	return f
}

// QueryTx 设置为手动事务
func (f *_first) QueryTx(tx *query.QueryTx) *_first {
	f.qTx = tx
	if tx != nil {
		f.tx = nil
	}
	return f
}

func (f *_first) Select(field ...field.Expr) *_first {
	f.selects = append(f.selects, field...)
	return f
}

func (f *_first) ForUpdate() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return f
}

func (f *_first) ForUpdateSkipLocked() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_first) ForUpdateNoWait() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_first) ForShare() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return f
}

func (f *_first) ForShareSkipLocked() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_first) ForShareNoWait() *_first {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_first) Unscoped() *_first {
	f.unscoped = true
	return f
}

func (f *_first) Relation(opts ...RelationOption) *_first {
	f.relationOpts = append(f.relationOpts, opts...)
	return f
}

func (f *_first) Where(opts ...ConditionOption) *_first {
	f.conditionOpts = append(f.conditionOpts, opts...)
	return f
}

// Do 执行获取第一条记录（主键升序）
func (f *_first) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	fq := f.core.q.{{.StructName}}
	if f.tx != nil {
		fq = f.tx.{{.StructName}}
	}
	if f.qTx != nil {
		fq = f.qTx.{{.StructName}}
	}
	fr := fq.WithContext(ctx)
	if f.core.newTableName != nil && *f.core.newTableName != "" {
		fr = fq.Table(*f.core.newTableName).WithContext(ctx)
	}
	if len(f.selects) > 0 {
		if f.core.newTableName == nil {
			fr = fr.Select(f.selects...)
		} else {
			fs := make([]field.Expr, 0, len(f.selects))
			for _, v := range f.selects {
				fs = append(fs, field.NewField(*f.core.newTableName, v.ColumnName().String()))
			}
			fr = fr.Select(fs...)
		}
	}
	if f.unscoped {
		fr = fr.Unscoped()
	}
	if (f.tx != nil || f.qTx != nil) && f.lock != nil {
		fr = fr.Clauses(f.lock)
	}
	if len(f.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(f.conditionOpts))
		for _, opt := range f.conditionOpts {
			conditions = append(conditions, opt(f.core))
		}
		if len(conditions) > 0 {
			fr = fr.Where(conditions...)
		}
	}
	if len(f.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(f.relationOpts))
		for _, opt := range f.relationOpts {
			relations = append(relations, opt(f.core))
		}
		if len(relations) > 0 {
			fr = fr.Preload(relations...)
		}
	}
	res, err := fr.First()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			f.core.logger.Error("【{{.StructName}}.First】失败", zap.Error(err))
		}
		return nil, err
	}
	return res, nil
}
`
}

func (r *Repository) genLastTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _last struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	conditionOpts []ConditionOption
}

// Last 获取最后一条记录（主键降序）
func ({{.Abbr}} *{{.StructName}}) Last() *_last {
	return &_last{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (l *_last) Tx(tx *query.Query) *_last {
	l.tx = tx
	if tx != nil {
		l.qTx = nil
	}
	return l
}

// QueryTx 设置为手动事务
func (l *_last) QueryTx(tx *query.QueryTx) *_last {
	l.qTx = tx
	if tx != nil {
		l.tx = nil
	}
	return l
}

func (l *_last) Select(field ...field.Expr) *_last {
	l.selects = append(l.selects, field...)
	return l
}

func (l *_last) ForUpdate() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *_last) ForUpdateSkipLocked() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_last) ForUpdateNoWait() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_last) ForShare() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *_last) ForShareSkipLocked() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_last) ForShareNoWait() *_last {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_last) Unscoped() *_last {
	l.unscoped = true
	return l
}

func (l *_last) Relation(opts ...RelationOption) *_last {
	l.relationOpts = append(l.relationOpts, opts...)
	return l
}

func (l *_last) Where(opts ...ConditionOption) *_last {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

// Do 执行获取最后一条记录（主键降序）
func (l *_last) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	lq := l.core.q.{{.StructName}}
	if l.tx != nil {
		lq = l.tx.{{.StructName}}
	}
	if l.qTx != nil {
		lq = l.qTx.{{.StructName}}
	}
	lr := lq.WithContext(ctx)
	if l.core.newTableName != nil && *l.core.newTableName != "" {
		lr = lq.Table(*l.core.newTableName).WithContext(ctx)
	}
	if len(l.selects) > 0 {
		if l.core.newTableName == nil {
			lr = lr.Select(l.selects...)
		} else {
			fs := make([]field.Expr, 0, len(l.selects))
			for _, v := range l.selects {
				fs = append(fs, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
			lr = lr.Select(fs...)
		}
	}
	if l.unscoped {
		lr = lr.Unscoped()
	}
	if (l.tx != nil || l.qTx != nil) && l.lock != nil {
		lr = lr.Clauses(l.lock)
	}
	if len(l.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(l.conditionOpts))
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
		if len(conditions) > 0 {
			lr = lr.Where(conditions...)
		}
	}
	if len(l.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(l.relationOpts))
		for _, opt := range l.relationOpts {
			relations = append(relations, opt(l.core))
		}
		if len(relations) > 0 {
			lr = lr.Preload(relations...)
		}
	}
	res, err := lr.Last()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			l.core.logger.Error("【{{.StructName}}.Last】失败", zap.Error(err))
		}
		return nil, err
	}
	return res, nil
}
`
}

func (r *Repository) genListTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

    "github.com/gorm-gen/plugin/paginate"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _list struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	page          int
	pageSize      int
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	orderOpts     []OrderOption
	conditionOpts []ConditionOption
}

// List 获取数据列表
func ({{.Abbr}} *{{.StructName}}) List() *_list {
	return &_list{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		orderOpts:     make([]OrderOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (l *_list) Tx(tx *query.Query) *_list {
	l.tx = tx
	if tx != nil {
		l.qTx = nil
	}
	return l
}

// QueryTx 设置为手动事务
func (l *_list) QueryTx(tx *query.QueryTx) *_list {
	l.qTx = tx
	if tx != nil {
		l.tx = nil
	}
	return l
}

func (l *_list) Select(field ...field.Expr) *_list {
	l.selects = append(l.selects, field...)
	return l
}

func (l *_list) ForUpdate() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *_list) ForUpdateSkipLocked() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_list) ForUpdateNoWait() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_list) ForShare() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *_list) ForShareSkipLocked() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_list) ForShareNoWait() *_list {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_list) Unscoped() *_list {
	l.unscoped = true
	return l
}

func (l *_list) Relation(opts ...RelationOption) *_list {
	l.relationOpts = append(l.relationOpts, opts...)
	return l
}

func (l *_list) Order(opts ...OrderOption) *_list {
	l.orderOpts = append(l.orderOpts, opts...)
	return l
}

func (l *_list) Where(opts ...ConditionOption) *_list {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

// Page 列表分页
func (l *_list) Page(page, pageSize uint) *_list {
	l.page = int(page)
	l.pageSize = int(pageSize)
	return l
}

// Do 执行获取数据列表
func (l *_list) Do(ctx context.Context) ([]*{{.ModelName}}.{{.StructName}}, error) {
	lq := l.core.q.{{.StructName}}
	if l.tx != nil {
		lq = l.tx.{{.StructName}}
	}
	if l.qTx != nil {
		lq = l.qTx.{{.StructName}}
	}
	lr := lq.WithContext(ctx)
	if l.core.newTableName != nil && *l.core.newTableName != "" {
		lr = lq.Table(*l.core.newTableName).WithContext(ctx)
	}
	if len(l.selects) > 0 {
		if l.core.newTableName == nil {
			lr = lr.Select(l.selects...)
		} else {
			fs := make([]field.Expr, 0, len(l.selects))
			for _, v := range l.selects {
				fs = append(fs, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
			lr = lr.Select(fs...)
		}
	}
	if l.unscoped {
		lr = lr.Unscoped()
	}
	if (l.tx != nil || l.qTx != nil) && l.lock != nil {
		lr = lr.Clauses(l.lock)
	}
	if len(l.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(l.conditionOpts))
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
		if len(conditions) > 0 {
			lr = lr.Where(conditions...)
		}
	}
	if len(l.orderOpts) > 0 {
		orders := make([]field.Expr, 0, len(l.orderOpts))
		for _, opt := range l.orderOpts {
			orders = append(orders, opt(l.core))
		}
		if len(orders) > 0 {
			lr = lr.Order(orders...)
		}
	}
	if l.page > 0 && l.pageSize > 0 {
		lr = lr.Scopes(paginate.Gen(l.page, l.pageSize))
	}
	if len(l.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(l.relationOpts))
		for _, opt := range l.relationOpts {
			relations = append(relations, opt(l.core))
		}
		if len(relations) > 0 {
			lr = lr.Preload(relations...)
		}
	}
	list, err := lr.Find()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			l.core.logger.Error("【{{.StructName}}.List】失败", zap.Error(err))
		}
		return nil, err
	}
	return list, nil
}
`
}

func (r *Repository) genTakeTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _take struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	relationOpts  []RelationOption
	orderOpts     []OrderOption
	conditionOpts []ConditionOption
}

// Take 获取一条记录
func ({{.Abbr}} *{{.StructName}}) Take() *_take {
	return &_take{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		relationOpts:  make([]RelationOption, 0),
		orderOpts:     make([]OrderOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (t *_take) Tx(tx *query.Query) *_take {
	t.tx = tx
	if tx != nil {
		t.qTx = nil
	}
	return t
}

// QueryTx 设置为手动事务
func (t *_take) QueryTx(tx *query.QueryTx) *_take {
	t.qTx = tx
	if tx != nil {
		t.tx = nil
	}
	return t
}

func (t *_take) Select(field ...field.Expr) *_take {
	t.selects = append(t.selects, field...)
	return t
}

func (t *_take) ForUpdate() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return t
}

func (t *_take) ForUpdateSkipLocked() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return t
}

func (t *_take) ForUpdateNoWait() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return t
}

func (t *_take) ForShare() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return t
}

func (t *_take) ForShareSkipLocked() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return t
}

func (t *_take) ForShareNoWait() *_take {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return t
}

func (t *_take) Unscoped() *_take {
	t.unscoped = true
	return t
}

func (t *_take) Relation(opts ...RelationOption) *_take {
	t.relationOpts = append(t.relationOpts, opts...)
	return t
}

func (t *_take) Order(opts ...OrderOption) *_take {
	t.orderOpts = append(t.orderOpts, opts...)
	return t
}

func (t *_take) Where(opts ...ConditionOption) *_take {
	t.conditionOpts = append(t.conditionOpts, opts...)
	return t
}

// Do 执行获取一条记录
func (t *_take) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	tq := t.core.q.{{.StructName}}
	if t.tx != nil {
		tq = t.tx.{{.StructName}}
	}
	if t.qTx != nil {
		tq = t.qTx.{{.StructName}}
	}
	tr := tq.WithContext(ctx)
	if t.core.newTableName != nil && *t.core.newTableName != "" {
		tr = tq.Table(*t.core.newTableName).WithContext(ctx)
	}
	if len(t.selects) > 0 {
		if t.core.newTableName == nil {
			tr = tr.Select(t.selects...)
		} else {
			fs := make([]field.Expr, 0, len(t.selects))
			for _, v := range t.selects {
				fs = append(fs, field.NewField(*t.core.newTableName, v.ColumnName().String()))
			}
			tr = tr.Select(fs...)
		}
	}
	if t.unscoped {
		tr = tr.Unscoped()
	}
	if (t.tx != nil || t.qTx != nil) && t.lock != nil {
		tr = tr.Clauses(t.lock)
	}
	if len(t.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(t.conditionOpts))
		for _, opt := range t.conditionOpts {
			conditions = append(conditions, opt(t.core))
		}
		if len(conditions) > 0 {
			tr = tr.Where(conditions...)
		}
	}
	if len(t.orderOpts) > 0 {
		orders := make([]field.Expr, 0, len(t.orderOpts))
		for _, opt := range t.orderOpts {
			orders = append(orders, opt(t.core))
		}
		if len(orders) > 0 {
			tr = tr.Order(orders...)
		}
	}
	if len(t.relationOpts) > 0 {
		relations := make([]field.RelationField, 0, len(t.relationOpts))
		for _, opt := range t.relationOpts {
			relations = append(relations, opt(t.core))
		}
		if len(relations) > 0 {
			tr = tr.Preload(relations...)
		}
	}
	res, err := tr.Take()
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			t.core.logger.Error("【{{.StructName}}.Take】失败", zap.Error(err))
		}
		return nil, err
	}
	return res, nil
}
`
}

func (r *Repository) genUpdateTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _update struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	updateOpts    []UpdateOption
	conditionOpts []ConditionOption
}

// Update 更新数据
func ({{.Abbr}} *{{.StructName}}) Update() *_update {
	return &_update{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		updateOpts:    make([]UpdateOption, 0),
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (u *_update) Tx(tx *query.Query) *_update {
	u.tx = tx
	if tx != nil {
		u.qTx = nil
	}
	return u
}

// QueryTx 设置为手动事务
func (u *_update) QueryTx(tx *query.QueryTx) *_update {
	u.qTx = tx
	if tx != nil {
		u.tx = nil
	}
	return u
}

func (u *_update) Unscoped() *_update {
	u.unscoped = true
	return u
}

func (u *_update) Update(opts ...UpdateOption) *_update {
	u.updateOpts = append(u.updateOpts, opts...)
	return u
}

func (u *_update) Where(opts ...ConditionOption) *_update {
	u.conditionOpts = append(u.conditionOpts, opts...)
	return u
}

// Do 执行更新数据
func (u *_update) Do(ctx context.Context) (int64, error) {
	if len(u.updateOpts) == 0 {
		return 0, nil
	}
	uq := u.core.q.{{.StructName}}
	if u.tx != nil {
		uq = u.tx.{{.StructName}}
	}
	if u.qTx != nil {
		uq = u.qTx.{{.StructName}}
	}
	ur := uq.WithContext(ctx)
	if u.core.newTableName != nil && *u.core.newTableName != "" {
		ur = uq.Table(*u.core.newTableName).WithContext(ctx)
	}
	if u.unscoped {
		ur = ur.Unscoped()
	}
	if len(u.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(u.conditionOpts))
		for _, opt := range u.conditionOpts {
			conditions = append(conditions, opt(u.core))
		}
		if len(conditions) > 0 {
			ur = ur.Where(conditions...)
		}
	}
	columns := make([]field.AssignExpr, 0, len(u.updateOpts))
	for _, opt := range u.updateOpts {
		columns = append(columns, opt(u.core))
	}
	if len(columns) == 0 {
		return 0, nil
	}
	res, err := ur.UpdateSimple(columns...)
	if err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			u.core.logger.Error("【{{.StructName}}.Update】失败", zap.Error(err))
		}
		return 0, err
	}
	return res.RowsAffected, nil
}
`
}

func (r *Repository) genSumTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _sum struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	genField      field.Expr
	conditionOpts []ConditionOption
}

// Sum SUM数据
func ({{.Abbr}} *{{.StructName}}) Sum(genField field.Expr) *_sum {
	return &_sum{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		genField:      genField,
		conditionOpts: make([]ConditionOption, 0),
	}
}

// Tx 设置为事务
func (s *_sum) Tx(tx *query.Query) *_sum {
	s.tx = tx
	if tx != nil {
		s.qTx = nil
	}
	return s
}

// QueryTx 设置为手动事务
func (s *_sum) QueryTx(tx *query.QueryTx) *_sum {
	s.qTx = tx
	if tx != nil {
		s.tx = nil
	}
	return s
}

func (s *_sum) Unscoped() *_sum {
	s.unscoped = true
	return s
}

func (s *_sum) Where(opts ...ConditionOption) *_sum {
	s.conditionOpts = append(s.conditionOpts, opts...)
	return s
}
` + "\ntype Sum struct {\n    Sum decimal.Decimal `json:\"sum\"`\n}\n\n" + `// Do 执行SUM数据
func (s *_sum) Do(ctx context.Context) (decimal.Decimal, error) {
	sq := s.core.q.{{.StructName}}
	if s.tx != nil {
		sq = s.tx.{{.StructName}}
	}
	if s.qTx != nil {
		sq = s.qTx.{{.StructName}}
	}
	expr := field.NewField("", s.genField.ColumnName().String()).Sum().As("sum")
	sr := sq.WithContext(ctx)
	if s.core.newTableName != nil && *s.core.newTableName != "" {
		sr = sq.Table(*s.core.newTableName).WithContext(ctx)
	}
	sr = sr.Select(expr)
	if s.unscoped {
		sr = sr.Unscoped()
	}
	if len(s.conditionOpts) > 0 {
		conditions := make([]gen.Condition, 0, len(s.conditionOpts))
		for _, opt := range s.conditionOpts {
			conditions = append(conditions, opt(s.core))
		}
		if len(conditions) > 0 {
			sr = sr.Where(conditions...)
		}
	}
	var data Sum
	if err := sr.Scan(&data); err != nil {
		if {{.RepoPkgName}}.IsRealErr(err) {
			s.core.logger.Error("【{{.StructName}}.Sum】失败", zap.Error(err))
		}
		return decimal.Zero, err
	}
	return data.Sum, nil
}
`
}

func (r *Repository) genMultiCountTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _multiCount struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiCount 获取多表数据总记录
func ({{.Abbr}} *{{.StructName}}) MultiCount(sharding []{{.ShardingKeyType}}) *_multiCount {
	return &_multiCount{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (c *_multiCount) Worker(worker chan struct{}) *_multiCount {
	if worker == nil {
		return c
	}
	c.worker = worker
	return c
}

// Tx 设置为事务
func (c *_multiCount) Tx(tx *query.Query) *_multiCount {
	c.tx = tx
	c.qTx = nil
	return c
}

// QueryTx 设置为手动事务
func (c *_multiCount) QueryTx(tx *query.QueryTx) *_multiCount {
	c.qTx = tx
	c.tx = nil
	return c
}

func (c *_multiCount) Unscoped() *_multiCount {
	c.unscoped = true
	return c
}

func (c *_multiCount) Where(opts ...ConditionOption) *_multiCount {
	c.conditionOpts = append(c.conditionOpts, opts...)
	return c
}

// Do 执行获取多表数据总记录
func (c *_multiCount) Do(ctx context.Context) (int64, map[{{.ShardingKeyType}}]int64, error) {
	if len(c.sharding) == 0 {
		return 0, nil, nil
	}
	cq := c.core.q.{{.StructName}}
	if c.tx != nil {
		cq = c.tx.{{.StructName}}
	}
	if c.qTx != nil {
		cq = c.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(c.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(c.conditionOpts))
		for _, opt := range c.conditionOpts {
			conditions = append(conditions, opt(c.core))
		}
	}
	sm := sync.Map{}
	wg := sync.WaitGroup{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range c.sharding {
		c.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					c.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiCount.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}c.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(c.core))
			cr := cq.WithContext(ctx)
			if c.unscoped {
				cr = cr.Unscoped()
			}
			count, err := cr.Where(_conditions...).Count()
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					c.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiCount.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				errChan {{.ChanSign}} err
				return
			}
			sm.Store(sharding, count)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case {{.ChanSign}}endChan:
		count := int64(0)
		m := make(map[{{.ShardingKeyType}}]int64, len(c.sharding))
		sm.Range(func(key, value interface{}) bool {
			v := value.(int64)
			m[key.({{.ShardingKeyType}})] = v
			count += v
			return true
		})
		return count, m, nil
	case err := {{.ChanSign}}errChan:
		return 0, nil, err
	}
}
`
}

func (r *Repository) genMultiDeleteTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _multiDelete struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiDelete 删除多表数据
func ({{.Abbr}} *{{.StructName}}) MultiDelete(sharding []{{.ShardingKeyType}}) *_multiDelete {
	return &_multiDelete{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (d *_multiDelete) Worker(worker chan struct{}) *_multiDelete {
	if worker == nil {
		return d
	}
	d.worker = worker
	return d
}

// Tx 设置为事务
func (d *_multiDelete) Tx(tx *query.Query) *_multiDelete {
	d.tx = tx
	if tx != nil {
		d.qTx = nil
	}
	return d
}

// QueryTx 设置为手动事务
func (d *_multiDelete) QueryTx(tx *query.QueryTx) *_multiDelete {
	d.qTx = tx
	if tx != nil {
		d.tx = nil
	}
	return d
}

func (d *_multiDelete) Unscoped() *_multiDelete {
	d.unscoped = true
	return d
}

func (d *_multiDelete) Where(opts ...ConditionOption) *_multiDelete {
	d.conditionOpts = append(d.conditionOpts, opts...)
	return d
}

// Do 执行删除多表数据
func (d *_multiDelete) Do(ctx context.Context) (int64, map[{{.ShardingKeyType}}]int64, error) {
	if len(d.sharding) == 0 {
		return 0, nil, nil
	}
	dq := d.core.q.{{.StructName}}
	if d.tx != nil {
		dq = d.tx.{{.StructName}}
	}
	if d.qTx != nil {
		dq = d.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(d.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(d.conditionOpts))
		for _, opt := range d.conditionOpts {
			conditions = append(conditions, opt(d.core))
		}
	}
	sm := sync.Map{}
	wg := sync.WaitGroup{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range d.sharding {
		d.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					d.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiDelete.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}d.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(d.core))
			dr := dq.WithContext(ctx)
			if d.unscoped {
				dr = dr.Unscoped()
			}
			res, err := dr.Where(_conditions...).Delete()
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					d.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiDelete.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				errChan {{.ChanSign}} err
				return
			}
			sm.Store(sharding, res.RowsAffected)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case {{.ChanSign}}endChan:
		rowsAffected := int64(0)
		m := make(map[{{.ShardingKeyType}}]int64, len(d.sharding))
		sm.Range(func(key, value interface{}) bool {
			v := value.(int64)
			m[key.({{.ShardingKeyType}})] = v
			rowsAffected += v
			return true
		})
		return rowsAffected, m, nil
	case err := {{.ChanSign}}errChan:
		return 0, nil, err
	}
}
`
}

func (r *Repository) genMultiFirstTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _multiFirst struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiFirst 获取多表随机第一条记录（主键升序）
func ({{.Abbr}} *{{.StructName}}) MultiFirst(sharding []{{.ShardingKeyType}}) *_multiFirst {
	return &_multiFirst{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (f *_multiFirst) Worker(worker chan struct{}) *_multiFirst {
	if worker == nil {
		return f
	}
	f.worker = worker
	return f
}

// Tx 设置为事务
func (f *_multiFirst) Tx(tx *query.Query) *_multiFirst {
	f.tx = tx
	if tx != nil {
		f.qTx = nil
	}
	return f
}

// QueryTx 设置为手动事务
func (f *_multiFirst) QueryTx(tx *query.QueryTx) *_multiFirst {
	f.qTx = tx
	if tx != nil {
		f.tx = nil
	}
	return f
}

func (f *_multiFirst) Select(field ...field.Expr) *_multiFirst {
	f.selects = append(f.selects, field...)
	return f
}

func (f *_multiFirst) ForUpdate() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return f
}

func (f *_multiFirst) ForUpdateSkipLocked() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_multiFirst) ForUpdateNoWait() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_multiFirst) ForShare() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return f
}

func (f *_multiFirst) ForShareSkipLocked() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return f
}

func (f *_multiFirst) ForShareNoWait() *_multiFirst {
	f.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return f
}

func (f *_multiFirst) Unscoped() *_multiFirst {
	f.unscoped = true
	return f
}

func (f *_multiFirst) Where(opts ...ConditionOption) *_multiFirst {
	f.conditionOpts = append(f.conditionOpts, opts...)
	return f
}

// Do 执行获取多表随机第一条记录（主键升序）
func (f *_multiFirst) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	if len(f.sharding) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	fq := f.core.q.{{.StructName}}
	if f.tx != nil {
		fq = f.tx.{{.StructName}}
	}
	if f.qTx != nil {
		fq = f.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(f.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(f.conditionOpts))
		for _, opt := range f.conditionOpts {
			conditions = append(conditions, opt(f.core))
		}
	}
	var fieldExpr []field.Expr
	if len(f.selects) > 0 {
		fieldExpr = make([]field.Expr, 0, len(f.selects))
		if f.core.newTableName == nil {
			fieldExpr = append(fieldExpr, f.selects...)
		} else {
			for _, v := range f.selects {
				fieldExpr = append(fieldExpr, field.NewField(*f.core.newTableName, v.ColumnName().String()))
			}
		}
	}
	wg := sync.WaitGroup{}
	endChan := make(chan struct{})
	errChan := make(chan error)
	resultChan := make(chan *{{.ModelName}}.{{.StructName}})
	for _, sharding := range f.sharding {
		f.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					f.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiFirst.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}f.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(f.core))
			fr := fq.WithContext(ctx)
			if len(fieldExpr) > 0 {
				fr = fr.Select(fieldExpr...)
			}
			if f.unscoped {
				fr = fr.Unscoped()
			}
			if (f.tx != nil || f.qTx != nil) && f.lock != nil {
				fr = fr.Clauses(f.lock)
			}
			res, err := fr.Where(_conditions...).First()
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					f.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiFirst.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				if !errors.Is(err, gorm.ErrRecordNotFound) {
					errChan {{.ChanSign}} err
				}
				return
			}
			resultChan {{.ChanSign}} res
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case res := {{.ChanSign}}resultChan:
		return res, nil
	case {{.ChanSign}}endChan:
		return nil, gorm.ErrRecordNotFound
	case err := {{.ChanSign}}errChan:
		return nil, err
	}
}
`
}

func (r *Repository) genMultiLastTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _multiLast struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiLast 获取多表随机最后一条记录（主键降序）
func ({{.Abbr}} *{{.StructName}}) MultiLast(sharding []{{.ShardingKeyType}}) *_multiLast {
	return &_multiLast{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (l *_multiLast) Worker(worker chan struct{}) *_multiLast {
	if worker == nil {
		return l
	}
	l.worker = worker
	return l
}

// Tx 设置为事务
func (l *_multiLast) Tx(tx *query.Query) *_multiLast {
	l.tx = tx
	if tx != nil {
		l.qTx = nil
	}
	return l
}

// QueryTx 设置为手动事务
func (l *_multiLast) QueryTx(tx *query.QueryTx) *_multiLast {
	l.qTx = tx
	if tx != nil {
		l.tx = nil
	}
	return l
}

func (l *_multiLast) Select(field ...field.Expr) *_multiLast {
	l.selects = append(l.selects, field...)
	return l
}

func (l *_multiLast) ForUpdate() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return l
}

func (l *_multiLast) ForUpdateSkipLocked() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_multiLast) ForUpdateNoWait() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_multiLast) ForShare() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return l
}

func (l *_multiLast) ForShareSkipLocked() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return l
}

func (l *_multiLast) ForShareNoWait() *_multiLast {
	l.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return l
}

func (l *_multiLast) Unscoped() *_multiLast {
	l.unscoped = true
	return l
}

func (l *_multiLast) Where(opts ...ConditionOption) *_multiLast {
	l.conditionOpts = append(l.conditionOpts, opts...)
	return l
}

// Do 执行获取多表随机最后一条记录（主键降序）
func (l *_multiLast) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	if len(l.sharding) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	fq := l.core.q.{{.StructName}}
	if l.tx != nil {
		fq = l.tx.{{.StructName}}
	}
	if l.qTx != nil {
		fq = l.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(l.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(l.conditionOpts))
		for _, opt := range l.conditionOpts {
			conditions = append(conditions, opt(l.core))
		}
	}
	var fieldExpr []field.Expr
	if len(l.selects) > 0 {
		fieldExpr = make([]field.Expr, 0, len(l.selects))
		if l.core.newTableName == nil {
			fieldExpr = append(fieldExpr, l.selects...)
		} else {
			for _, v := range l.selects {
				fieldExpr = append(fieldExpr, field.NewField(*l.core.newTableName, v.ColumnName().String()))
			}
		}
	}
	wg := sync.WaitGroup{}
	endChan := make(chan struct{})
	errChan := make(chan error)
	resultChan := make(chan *{{.ModelName}}.{{.StructName}})
	for _, sharding := range l.sharding {
		l.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					l.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiLast.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}l.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(l.core))
			fr := fq.WithContext(ctx)
			if len(fieldExpr) > 0 {
				fr = fr.Select(fieldExpr...)
			}
			if l.unscoped {
				fr = fr.Unscoped()
			}
			if (l.tx != nil || l.qTx != nil) && l.lock != nil {
				fr = fr.Clauses(l.lock)
			}
			res, err := fr.Where(_conditions...).Last()
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					l.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiLast.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				if !errors.Is(err, gorm.ErrRecordNotFound) {
					errChan {{.ChanSign}} err
				}
				return
			}
			resultChan {{.ChanSign}} res
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case res := {{.ChanSign}}resultChan:
		return res, nil
	case {{.ChanSign}}endChan:
		return nil, gorm.ErrRecordNotFound
	case err := {{.ChanSign}}errChan:
		return nil, err
	}
}
`
}

func (r *Repository) genMultiListTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}
`
}

func (r *Repository) genMultiSumTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"github.com/shopspring/decimal"
	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _multiSum struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	genField      field.Expr
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiSum 多表SUM数据
func ({{.Abbr}} *{{.StructName}}) MultiSum(genField field.Expr, sharding []{{.ShardingKeyType}}) *_multiSum {
	return &_multiSum{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		genField:      genField,
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (s *_multiSum) Worker(worker chan struct{}) *_multiSum {
	if worker == nil {
		return s
	}
	s.worker = worker
	return s
}

// Tx 设置为事务
func (s *_multiSum) Tx(tx *query.Query) *_multiSum {
	s.tx = tx
	if tx != nil {
		s.qTx = nil
	}
	return s
}

// QueryTx 设置为手动事务
func (s *_multiSum) QueryTx(tx *query.QueryTx) *_multiSum {
	s.qTx = tx
	if tx != nil {
		s.tx = nil
	}
	return s
}

func (s *_multiSum) Unscoped() *_multiSum {
	s.unscoped = true
	return s
}

func (s *_multiSum) Where(opts ...ConditionOption) *_multiSum {
	s.conditionOpts = append(s.conditionOpts, opts...)
	return s
}

// Do 执行多表SUM数据
func (s *_multiSum) Do(ctx context.Context) (decimal.Decimal, map[{{.ShardingKeyType}}]decimal.Decimal, error) {
	if len(s.sharding) == 0 {
		return decimal.Zero, nil, nil
	}
	sq := s.core.q.{{.StructName}}
	if s.tx != nil {
		sq = s.tx.{{.StructName}}
	}
	if s.qTx != nil {
		sq = s.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(s.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(s.conditionOpts))
		for _, opt := range s.conditionOpts {
			conditions = append(conditions, opt(s.core))
		}
	}
	expr := field.NewField("", s.genField.ColumnName().String()).Sum().As("sum")
	wg := sync.WaitGroup{}
	sm := sync.Map{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range s.sharding {
		s.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					s.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiSum.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}s.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(s.core))
			sr := sq.WithContext(ctx).Select(expr)
			if s.unscoped {
				sr = sr.Unscoped()
			}
			var data Sum
			if err := sr.Where(_conditions...).Scan(&data); err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					s.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiSum.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				errChan {{.ChanSign}} err
				return
			}
			sm.Store(sharding, data.Sum)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case {{.ChanSign}}endChan:
		sum := decimal.Zero
		m := make(map[{{.ShardingKeyType}}]decimal.Decimal, len(s.sharding))
		sm.Range(func(key, value interface{}) bool {
			v := value.(decimal.Decimal)
			m[key.({{.ShardingKeyType}})] = v
			sum = sum.Add(v)
			return true
		})
		return sum, m, nil
	case err := {{.ChanSign}}errChan:
		return decimal.Zero, nil, err
	}
}
`
}

func (r *Repository) genMultiTakeTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"

	"{{.ModelPkg}}"
)

type _multiTake struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	lock          clause.Expression
	unscoped      bool
	selects       []field.Expr
	orderOpts     []OrderOption
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiTake 获取多表随机一条记录
func ({{.Abbr}} *{{.StructName}}) MultiTake(sharding []{{.ShardingKeyType}}) *_multiTake {
	return &_multiTake{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		selects:       make([]field.Expr, 0),
		orderOpts:     make([]OrderOption, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (t *_multiTake) Worker(worker chan struct{}) *_multiTake {
	if worker == nil {
		return t
	}
	t.worker = worker
	return t
}

// Tx 设置为事务
func (t *_multiTake) Tx(tx *query.Query) *_multiTake {
	t.tx = tx
	if tx != nil {
		t.qTx = nil
	}
	return t
}

// QueryTx 设置为手动事务
func (t *_multiTake) QueryTx(tx *query.QueryTx) *_multiTake {
	t.qTx = tx
	if tx != nil {
		t.tx = nil
	}
	return t
}

func (t *_multiTake) Select(field ...field.Expr) *_multiTake {
	t.selects = append(t.selects, field...)
	return t
}

func (t *_multiTake) ForUpdate() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate}
	return t
}

func (t *_multiTake) ForUpdateSkipLocked() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsSkipLocked}
	return t
}

func (t *_multiTake) ForUpdateNoWait() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthUpdate, Options: clause.LockingOptionsNoWait}
	return t
}

func (t *_multiTake) ForShare() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare}
	return t
}

func (t *_multiTake) ForShareSkipLocked() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsSkipLocked}
	return t
}

func (t *_multiTake) ForShareNoWait() *_multiTake {
	t.lock = clause.Locking{Strength: clause.LockingStrengthShare, Options: clause.LockingOptionsNoWait}
	return t
}

func (t *_multiTake) Unscoped() *_multiTake {
	t.unscoped = true
	return t
}

func (t *_multiTake) Order(opts ...OrderOption) *_multiTake {
	t.orderOpts = append(t.orderOpts, opts...)
	return t
}

func (t *_multiTake) Where(opts ...ConditionOption) *_multiTake {
	t.conditionOpts = append(t.conditionOpts, opts...)
	return t
}

// Do 执行获取多表随机一条记录
func (t *_multiTake) Do(ctx context.Context) (*{{.ModelName}}.{{.StructName}}, error) {
	if len(t.sharding) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	fq := t.core.q.{{.StructName}}
	if t.tx != nil {
		fq = t.tx.{{.StructName}}
	}
	if t.qTx != nil {
		fq = t.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(t.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(t.conditionOpts))
		for _, opt := range t.conditionOpts {
			conditions = append(conditions, opt(t.core))
		}
	}
	var fieldExpr []field.Expr
	if len(t.selects) > 0 {
		fieldExpr = make([]field.Expr, 0, len(t.selects))
		if t.core.newTableName == nil {
			fieldExpr = append(fieldExpr, t.selects...)
		} else {
			for _, v := range t.selects {
				fieldExpr = append(fieldExpr, field.NewField(*t.core.newTableName, v.ColumnName().String()))
			}
		}
	}
	var orders []field.Expr
	if len(t.orderOpts) > 0 {
		orders = make([]field.Expr, 0, len(t.orderOpts))
		for _, opt := range t.orderOpts {
			orders = append(orders, opt(t.core))
		}
	}
	wg := sync.WaitGroup{}
	endChan := make(chan struct{})
	errChan := make(chan error)
	resultChan := make(chan *{{.ModelName}}.{{.StructName}})
	for _, sharding := range t.sharding {
		t.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					t.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiTake.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}t.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(t.core))
			fr := fq.WithContext(ctx)
			if len(fieldExpr) > 0 {
				fr = fr.Select(fieldExpr...)
			}
			if t.unscoped {
				fr = fr.Unscoped()
			}
			if (t.tx != nil || t.qTx != nil) && t.lock != nil {
				fr = fr.Clauses(t.lock)
			}
			fr = fr.Where(_conditions...)
			if len(orders) > 0 {
				fr = fr.Order(orders...)
			}
			res, err := fr.Take()
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					t.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiTake.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				if !errors.Is(err, gorm.ErrRecordNotFound) {
					errChan {{.ChanSign}} err
				}
				return
			}
			resultChan {{.ChanSign}} res
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case res := {{.ChanSign}}resultChan:
		return res, nil
	case {{.ChanSign}}endChan:
		return nil, gorm.ErrRecordNotFound
	case err := {{.ChanSign}}errChan:
		return nil, err
	}
}
`
}

func (r *Repository) genMultiUpdateTemplate() string {
	return `// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.
// Code generated by github.com/gorm-gen/plugin/repository. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"

	"go.uber.org/zap"
	"gorm.io/gen"
	"gorm.io/gen/field"

	"{{.GenQueryPkg}}"

	"{{.RepoPkg}}"
)

type _multiUpdate struct {
	core          *{{.StructName}}
	tx            *query.Query
	qTx           *query.QueryTx
	unscoped      bool
	updateOpts    []UpdateOption
	conditionOpts []ConditionOption
	sharding      []{{.ShardingKeyType}}
	worker        chan struct{}
}

// MultiUpdate 更新多表数据
func ({{.Abbr}} *{{.StructName}}) MultiUpdate(sharding []{{.ShardingKeyType}}) *_multiUpdate {
	return &_multiUpdate{
		core:          {{.Abbr}},
		unscoped:      {{.Abbr}}.unscoped,
		updateOpts:    make([]UpdateOption, 0),
		conditionOpts: make([]ConditionOption, 0),
		sharding:      sharding,
		worker:        make(chan struct{}, runtime.NumCPU()),
	}
}

func (u *_multiUpdate) Worker(worker chan struct{}) *_multiUpdate {
	if worker == nil {
		return u
	}
	u.worker = worker
	return u
}

// Tx 设置为事务
func (u *_multiUpdate) Tx(tx *query.Query) *_multiUpdate {
	u.tx = tx
	if tx != nil {
		u.qTx = nil
	}
	return u
}

// QueryTx 设置为手动事务
func (u *_multiUpdate) QueryTx(tx *query.QueryTx) *_multiUpdate {
	u.qTx = tx
	if tx != nil {
		u.tx = nil
	}
	return u
}

func (u *_multiUpdate) Unscoped() *_multiUpdate {
	u.unscoped = true
	return u
}

func (u *_multiUpdate) Update(opts ...UpdateOption) *_multiUpdate {
	u.updateOpts = append(u.updateOpts, opts...)
	return u
}

func (u *_multiUpdate) Where(opts ...ConditionOption) *_multiUpdate {
	u.conditionOpts = append(u.conditionOpts, opts...)
	return u
}

// Do 执行更新多表数据
func (u *_multiUpdate) Do(ctx context.Context) (int64, map[{{.ShardingKeyType}}]int64, error) {
	if len(u.updateOpts) == 0 || len(u.sharding) == 0 {
		return 0, nil, nil
	}
	uq := u.core.q.{{.StructName}}
	if u.tx != nil {
		uq = u.tx.{{.StructName}}
	}
	if u.qTx != nil {
		uq = u.qTx.{{.StructName}}
	}
	var conditions []gen.Condition
	if len(u.conditionOpts) > 0 {
		conditions = make([]gen.Condition, 0, len(u.conditionOpts))
		for _, opt := range u.conditionOpts {
			conditions = append(conditions, opt(u.core))
		}
	}
	columns := make([]field.AssignExpr, 0, len(u.updateOpts))
	for _, opt := range u.updateOpts {
		columns = append(columns, opt(u.core))
	}
	if len(columns) == 0 {
		return 0, nil, nil
	}
	sm := sync.Map{}
	wg := sync.WaitGroup{}
	errChan := make(chan error)
	endChan := make(chan struct{})
	for _, sharding := range u.sharding {
		u.worker {{.ChanSign}} struct{}{}
		wg.Add(1)
		go func(sharding {{.ShardingKeyType}}) {
			defer func() {
				if r := recover(); r != nil {
					u.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiUpdate.%{{.ShardingKeyTypeFormat}}】执行异常", sharding), zap.Any("recover", r), zap.ByteString("debug.Stack", debug.Stack()))
					errChan {{.ChanSign}} fmt.Errorf("recovered from panic: %v", r)
				}
			}()
			defer func() {
				{{.ChanSign}}u.worker
			}()
			defer wg.Done()
			_conditions := make([]gen.Condition, len(conditions))
			copy(_conditions, conditions)
			_conditions = append(_conditions, Condition{{.ShardingKey}}(sharding)(u.core))
			ur := uq.WithContext(ctx)
			if u.unscoped {
				ur = ur.Unscoped()
			}
			res, err := ur.Where(_conditions...).UpdateSimple(columns...)
			if err != nil {
				if {{.RepoPkgName}}.IsRealErr(err) {
					u.core.logger.Error(fmt.Sprintf("【{{.StructName}}.MultiUpdate.%{{.ShardingKeyTypeFormat}}】失败", sharding), zap.Error(err))
				}
				errChan {{.ChanSign}} err
				return
			}
			sm.Store(sharding, res.RowsAffected)
			return
		}(sharding)
	}
	go func() {
		wg.Wait()
		endChan {{.ChanSign}} struct{}{}
	}()
	select {
	case {{.ChanSign}}endChan:
		rowsAffected := int64(0)
		m := make(map[{{.ShardingKeyType}}]int64, len(u.sharding))
		sm.Range(func(key, value interface{}) bool {
			v := value.(int64)
			m[key.({{.ShardingKeyType}})] = v
			rowsAffected += v
			return true
		})
		return rowsAffected, m, nil
	case err := {{.ChanSign}}errChan:
		return 0, nil, err
	}
}
`
}
